#  Created by Erik Fernando Flores Quispe on 19/05/17.
#  Copyright © 2017 Belatrix. All rights reserved.

fastlane_version "2.30.0"

application_name = "Hackatrix"
channel_notification = "#iosteam"

project_base_url = sh("cd .. && pwd").strip!
changelog_configuration_source = "#{project_base_url}.changelogrc"
changelog_generation_output = "#{project_base_url}CHANGELOG.md"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "#{application_name}",
      workspace: "#{application_name}.xcworkspace",
      devices: ["iPhone 7"],
      clean: true,
      open_report: true
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :release do |options|
    #match(type: "appstore")
    increment_version_number(
      version_number: "#{options[:version]}"
    )
    increment_build_number(
      build_number: "#{options[:build]}"
    )
    cocoapods
    gym(
        scheme: "#{application_name}",
        export_method: "app-store"
    )
    sh("git-changelog -n #{options[:version]} --changelogrc #{changelog_configuration_source} --file #{changelog_generation_output}")
    git_tasks(options[:version], options[:build])
    pilot(
        skip_waiting_for_build_processing: true
    )
    clean_build_artifacts
    slack(
       message: "#{application_name} #{options[:version]} (#{get_build_number}) ya esta en testflight! 🎉 😎",
       channel: "#{channel_notification}"
    )
  end

  after_all do |lane|

  end

  error do |lane, exception|
    slack(
       message: "💩 #{exception.message} 💩",
       success: false,
        channel: "#{channel_notification}"
    )
  end
end

# Helper functions

def git_tasks(version, build)
  git_add(path:"./")
  git_commit(path:"./", message:"Versión #{version}")
  sh("git tag -a #{version} -m 'Se crea #{version}'")
  push_to_git_remote
  push_git_tags
end
